# Generated by Django 5.0.4 on 2024-06-19 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodtype',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('cost_time', models.IntegerField(default=0)),
                ('foodType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_manage.foodtype')),
            ],
        ),
    ]
